# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - couchspace-cms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://couchspacedev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab815370ecf045b7b6250eab65ee5101 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2ec4dca6bb4049b694fdab94ed326efc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: couchspacedev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab815370ecf045b7b6250eab65ee5101 }}/couchspacedev/couchspacedev/couchspace:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'couchspace-cms'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af2cbfc264f4468cbac726733e1d218c }}
        images: 'couchspacedev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab815370ecf045b7b6250eab65ee5101 }}/couchspacedev/couchspacedev/couchspace:${{ github.sha }}'