# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - couchspace-portal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://couchspacecms.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_90f2f9ec49d14adb838bd7d3b928c572 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bd7a2665c3f14beebd2f5cd53eb7da34 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: couchspacecms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_90f2f9ec49d14adb838bd7d3b928c572 }}/myimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'couchspace-portal'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0d3580cbeab4460dbf4a21e0f0a2f45f }}
        images: 'couchspacecms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_90f2f9ec49d14adb838bd7d3b928c572 }}/myimage:${{ github.sha }}'