# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - couchspace-portal-test

on:
  push:
    branches:
      - feature/20241107_Video
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://couchspacecms.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_429fd7a0a160464e98076e44d3f89a4f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61829b2da0d24536a81316d18a09c2c7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: couchspacecms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_429fd7a0a160464e98076e44d3f89a4f }}/couchspacecms/couchspacecms/myimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'couchspace-portal-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5a08930216644e9f95d0d3a40bec968f }}
        images: 'couchspacecms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_429fd7a0a160464e98076e44d3f89a4f }}/couchspacecms/couchspacecms/myimage:${{ github.sha }}'